---
title: "asset preparation mouse asymetry"
output: github_document
author: "Joanes Grandjean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load libraries}
#tidy stuff
library(tidyverse,warn.conflicts = FALSE)
library(glue,warn.conflicts = FALSE)

#easystat
library(datawizard,warn.conflicts = FALSE)
library(effectsize)
library(report)
```



## asset preparation and validation. 
the exisiting DSURQE label info is not very clear. Here I reshape it for better visualization.

```{r reshape the DSURQE label index}
roi_raw <- read_csv('asset/DSURQE_40micron_R_mapping.csv',col_types = cols())


roi_merge <- tibble(dsurqe_struct=c(glue('Right {roi_raw$Structure}'),glue('Left {roi_raw$Structure}')), 
                   abi_struct=c(glue('Right {roi_raw$ABI}'),glue('Left {roi_raw$ABI}')), 
                   tissue=c(roi_raw$`tissue type`, roi_raw$`tissue type`), 
                   label=c(roi_raw$`right label`, roi_raw$`left label`),
                   hemisphere=c(rep('right', dim(roi_raw)[1]), rep('left', dim(roi_raw)[1]))) %>% arrange(label)

duplicated_index <- duplicated(roi_merge$label)
duplicated_label <- roi_merge$label[duplicated_index]

roi_merge<-roi_merge[!duplicated_index,]

roi_merge$hemisphere[roi_merge$label %in% duplicated_label] <- 'inter'


write_csv(roi_merge, 'asset/roi_label_clean.csv')

report(roi_merge)
```



## find missing data and write to file. 
```{r list missing data}

vol_AI_list <- file.path(data_path,'vol_AI') %>% dir  %>% gsub("_01_SE01_MR.nii.gz","",.)
study$POND_Mouse_ID[which(!study$POND_Mouse_ID %in% vol_AI_list)] %>% as_tibble() %>%  write_csv('asset/missing.csv')

```

